#!/usr/bin/env python3
"""
Scrape ALL vehicle class fares for Ferizy classic routes.
Covers 12 vehicle classes (Gol I–IX) for all 4 Western Corridor OD routes.

Flow:
  1. POST /schedule/timesandkuota (fetch valid departure slot + kuota)
  2. GET  /ship_schedule (extract window.searchData token generated by backend)
  3. POST /schedule (fetch real fare envelope with vehicle breakdown)

Usage:  python3 scripts/scrape_fares_all_vehicle_classes.py [--date YYYY-MM-DD]
"""

import json
import csv
import os
import sys
import time
import re
import random
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed
import argparse
import requests

# ── Directories ───────────────────────────────────────────────
SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
DATA_ROOT = PROJECT_ROOT / "data" / "ferizy-classic-all"
FARES_DIR = DATA_ROOT / "fares"
CLASSIC_DATA_DIR = PROJECT_ROOT / "data" / "ferizy-classic"
EXPORTS_DIR = PROJECT_ROOT / "exports"

DATA_ROOT.mkdir(parents=True, exist_ok=True)
FARES_DIR.mkdir(parents=True, exist_ok=True)
CLASSIC_DATA_DIR.mkdir(parents=True, exist_ok=True)
EXPORTS_DIR.mkdir(parents=True, exist_ok=True)

# ── Ferizy API Constants ──────────────────────────────────────
BASE_URL = "https://ferizy.com"

# Map harbour id -> readable name
ORIGIN_NAMES = {
    "3": "Bakauheni",
    "2": "Merak",
    "4": "Gilimanuk",
    "5": "Ketapang",
}

SHIP_CLASS_NAMES = {
    "1": "Reguler",
    "2": "Express",
}

# Map vc id → readable name
VC_NAMES = {
    "4": "GOLONGAN I",
    "7": "GOLONGAN II",
    "8": "GOLONGAN III",
    "9": "GOLONGAN IVA",
    "10": "GOLONGAN IVB",
    "11": "GOLONGAN VA",
    "12": "GOLONGAN VB",
    "13": "GOLONGAN VIA",
    "14": "GOLONGAN VIB",
    "15": "GOLONGAN VII",
    "16": "GOLONGAN VIII",
    "17": "GOLONGAN IX",
}

# All 12 vehicle classes
VEHICLE_CLASSES = ["4", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17"]

# Ship classes per route pair
SHIP_CLASSES_PER_OD = {
    ("3", "2"): ["2", "1"],   # Bakauheni→Merak: Express(2) + Reguler(1)
    ("2", "3"): ["2", "1"],   # Merak→Bakauheni: Express(2) + Reguler(1)
    ("4", "5"): ["1"],        # Gilimanuk→Ketapang: Reguler only
    ("5", "4"): ["1"],        # Ketapang→Gilimanuk: Reguler only
}

# Service types: svc=1 = Pejalan Kaki, svc=2 = Kendaraan
SERVICE_TYPES = ["1", "2"]

USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"


def create_session() -> requests.Session:
    """Create and initialize a requests Session with cookies."""
    session = requests.Session()
    session.headers.update({
        "User-Agent": USER_AGENT,
        "Referer": f"{BASE_URL}/",
        "Accept": "*/*",
    })
    try:
        session.get(f"{BASE_URL}/", timeout=15)
    except Exception:
        pass
    return session


def parse_fare_json(body: dict) -> list[dict]:
    """Extract fare records from API response body dict."""
    data = body.get("data", {})
    if not isinstance(data, dict):
        return []
    sched = data.get("scheduleInfo", {})
    fare_v = data.get("fare", {}).get("vehicle", {})
    fare_a = data.get("fare", {}).get("adult", {})
    total = data.get("totalFare", {})
    avail = data.get("availability", {})
    
    amount = fare_v.get("amount") or total.get("amount") or 0
    
    return [{
        "depart_time_start": sched.get("depart_time_start", ""),
        "depart_time_end": sched.get("depart_time_end", ""),
        "available_quota": avail.get("available_quota", sched.get("kuota", "")),
        "total_amount": amount,
        "currency": total.get("currency", "IDR"),
        "ship_class_id": sched.get("ship_class_id", ""),
        "ship_class_name": sched.get("ship_class_name", ""),
        "service_name": sched.get("service_name", ""),
        "vehicle_name": sched.get("vehicle", {}).get("vehicle_name", ""),
    }]


def fetch_one(origin: str, destination: str, ship_class: str, vehicle_class: str, service: str, date: str) -> dict:
    """
    Fetch one fare request through the classic portal pipeline:
    timesandkuota -> ship_schedule -> POST /schedule
    """
    # Pejalan Kaki (service 1) does not use vehicle class IDs
    if service == "1":
        return {
            "success": True,
            "fare_count": 0,
            "error": None,
            "records": [],
            "status_label": "empty",
            "raw_envelope": None,
        }

    session = create_session()

    for attempt in range(3):
        try:
            # Step 1: Query timesandkuota for available time slot
            tk_url = f"{BASE_URL}/schedule/timesandkuota"
            tk_payload = {
                "service_id": service,
                "origin": origin,
                "destination": destination,
                "depart_date": date,
                "ship_class": ship_class,
                "vehicle_class_id": vehicle_class,
            }
            headers_ajax = {
                "User-Agent": USER_AGENT,
                "Referer": f"{BASE_URL}/",
                "X-Requested-With": "XMLHttpRequest",
            }
            tk_resp = session.post(tk_url, data=tk_payload, headers=headers_ajax, timeout=20)
            if tk_resp.status_code != 200:
                time.sleep(random.uniform(0.5, 1.2))
                continue
            
            try:
                tk_json = tk_resp.json()
            except json.JSONDecodeError:
                time.sleep(random.uniform(0.5, 1.2))
                continue

            times_list = [t for t in tk_json.get("times", []) if t.get("id") and not t.get("disabled")]
            if not times_list:
                return {
                    "success": True,
                    "fare_count": 0,
                    "error": None,
                    "records": [],
                    "status_label": "empty",
                    "raw_envelope": None,
                }

            chosen_slot = times_list[0]
            slot_parts = chosen_slot["id"].split("-")
            t_start = slot_parts[0]
            t_end = slot_parts[1]
            kuota = slot_parts[2] if len(slot_parts) > 2 else chosen_slot.get("kuota", "1000")

            # Step 2: GET ship_schedule page to obtain backend-encrypted window.searchData
            sched_page_url = f"{BASE_URL}/ship_schedule"
            sched_params = {
                "origin": origin,
                "destination": destination,
                "ship_class": ship_class,
                "depart_date": date,
                "depart_time_start": t_start,
                "depart_time_end": t_end,
                "service": service,
                "vehicle_class": vehicle_class,
                "kuota": kuota,
            }
            page_resp = session.get(sched_page_url, params=sched_params, headers={"User-Agent": USER_AGENT}, timeout=20)
            if page_resp.status_code != 200:
                time.sleep(random.uniform(0.5, 1.2))
                continue

            match = re.search(r"window\.searchData\s*=\s*(\{.*?\});", page_resp.text)
            if not match:
                time.sleep(random.uniform(0.5, 1.2))
                continue

            search_data = json.loads(match.group(1))

            # Step 3: POST /schedule with search_data
            headers_post = {
                "User-Agent": USER_AGENT,
                "Referer": page_resp.url,
                "X-Requested-With": "XMLHttpRequest",
            }
            fare_resp = session.post(f"{BASE_URL}/schedule", data=search_data, headers=headers_post, timeout=20)
            if fare_resp.status_code == 200:
                body = fare_resp.json()
                if body.get("code") == 1:
                    recs = parse_fare_json(body)
                    envelope = {
                        "origin": origin,
                        "destination": destination,
                        "ship_class": ship_class,
                        "vehicle_class": vehicle_class,
                        "depart_date": date,
                        "depart_time_start": t_start,
                        "depart_time_end": t_end,
                        "kuota": str(kuota),
                        "response": body,
                    }
                    return {
                        "success": True,
                        "fare_count": len(recs),
                        "error": None,
                        "records": recs,
                        "status_label": "OK",
                        "raw_envelope": envelope,
                        "depart_time_start": t_start,
                        "depart_time_end": t_end,
                        "kuota": str(kuota),
                    }
                else:
                    msg = body.get("message", f"code_{body.get('code')}")
                    return {
                        "success": False,
                        "fare_count": 0,
                        "error": f"response:{msg}",
                        "records": [],
                        "status_label": f"error:{msg}",
                        "raw_envelope": None,
                    }
        except (requests.exceptions.ConnectionError, requests.exceptions.Timeout) as e:
            if attempt < 2:
                time.sleep(random.uniform(1.0, 2.0))
                continue
            return {"success": False, "fare_count": None, "error": "timeout/retry", "records": [], "status_label": "timeout"}
        except Exception as e:
            return {"success": False, "fare_count": None, "error": str(e), "records": [], "status_label": "error"}

    return {"success": False, "fare_count": None, "error": "max_retries", "records": [], "status_label": "max_retries"}


def save_raw_fare(origin: str, dest: str, sc: str, vc: str, svc: str, date: str, envelope: dict) -> list[str]:
    """Save raw JSON envelopes to both ferizy-classic-all/fares and ferizy-classic."""
    saved_paths = []
    svc_label = "Kendaraan" if svc == "2" else "PejalanKaki"
    
    # 1. ferizy-classic-all/fares/
    fname_all = f"fare_{origin}_{dest}_{sc}_{svc_label}_vc{vc}_{date}.json"
    fp_all = FARES_DIR / fname_all
    fp_all.write_text(json.dumps(envelope, indent=2, ensure_ascii=False))
    saved_paths.append(str(fp_all))
    
    # 2. ferizy-classic/ (standard envelope matching legacy format)
    fname_classic = f"fare_{origin}_{dest}_{sc}_vc{vc}_{date}.json"
    fp_classic = CLASSIC_DATA_DIR / fname_classic
    fp_classic.write_text(json.dumps(envelope, indent=2, ensure_ascii=False))
    saved_paths.append(str(fp_classic))
    
    return saved_paths


def main():
    parser = argparse.ArgumentParser(description="Ferizy full vehicle class fare scraper")
    parser.add_argument("--date", default=None, help="Date to scrape (YYYY-MM-DD), default: today")
    args = parser.parse_args()

    DATE = args.date or time.strftime("%Y-%m-%d")

    print("=" * 75)
    print(f"Ferizy Full Vehicle Class Fare Scraper — {DATE}")
    print(f"Vehicle classes: {len(VEHICLE_CLASSES)} (Gol I–IX)")
    print(f"OD routes: 4 pairs × ship classes (6 ODxShip pairs) × 2 services = 144 tasks")
    print("=" * 75)

    all_matrix_rows = []
    unified_fare_rows = []
    stats = {"success": 0, "empty": 0, "failed": 0}

    # Build task list
    tasks = []
    for (orig, dest), ship_classes in SHIP_CLASSES_PER_OD.items():
        for svc in SERVICE_TYPES:
            svc_label = "Kendaraan" if svc == "2" else "PejalanKaki"
            for sc in ship_classes:
                for vc in VEHICLE_CLASSES:
                    tasks.append((orig, dest, sc, vc, svc, svc_label, DATE))

    total_tasks = len(tasks)
    print(f"\nTotal tasks: {total_tasks}")
    print("-" * 75)

    completed = 0
    with ThreadPoolExecutor(max_workers=4) as executor:
        fut_map = {}
        for orig, dest, sc, vc, svc, svc_label, d in tasks:
            future = executor.submit(fetch_one, orig, dest, sc, vc, svc, d)
            task_key = f"{orig}->{dest}|SC{sc}|{svc_label}|VC{vc}"
            fut_map[future] = (orig, dest, sc, vc, svc, svc_label, d, task_key)

        for future in as_completed(fut_map):
            orig, dest, sc, vc, svc, svc_label, d, task_key = fut_map[future]
            completed += 1
            od_display = f"{orig} → {dest}"
            sc_display = f"SC{sc}"
            vc_display = f"VC{vc}"
            vc_name = VC_NAMES.get(vc, f"GOLONGAN {vc}")

            try:
                result = future.result(timeout=45)
            except Exception as e:
                print(f"[{completed:3d}/{total_tasks}] ❌ {od_display} {sc_display} {svc_label:11s} {vc_display:4s} ({vc_name:13s}): ERROR {e}")
                stats["failed"] += 1
                all_matrix_rows.append({
                    "route": od_display,
                    "ship_class": sc_display,
                    "service": svc_label,
                    "vehicle_class": vc_display,
                    "vehicle_class_name": vc_name,
                    "depart_date": DATE,
                    "depart_time": "",
                    "available_quota": "",
                    "sample_total": "",
                    "currency": "",
                    "status": f"error: {str(e)[:60]}",
                    "fare_count": 0,
                    "sample_quota": "",
                })
                time.sleep(random.uniform(0.3, 0.6))
                continue

            matrix_row = {
                "route": od_display,
                "ship_class": sc_display,
                "service": svc_label,
                "vehicle_class": vc_display,
                "vehicle_class_name": vc_name,
                "depart_date": DATE,
                "depart_time": "",
                "available_quota": "",
                "sample_total": "",
                "currency": "IDR",
                "status": result.get("status_label", "unknown"),
                "fare_count": result.get("fare_count", 0),
                "sample_quota": "",
            }

            if result["success"] and result["records"]:
                stats["success"] += 1
                r0 = result["records"][0]
                dt_start = result.get("depart_time_start") or r0["depart_time_start"]
                dt_end = result.get("depart_time_end") or r0["depart_time_end"]
                quota = result.get("kuota") or str(r0["available_quota"])
                amt = r0["total_amount"]
                time_range = f"{dt_start}-{dt_end}"

                matrix_row.update({
                    "depart_time": time_range,
                    "available_quota": quota,
                    "sample_total": amt,
                    "sample_quota": quota,
                })

                # Save raw JSON envelopes
                if result.get("raw_envelope"):
                    save_raw_fare(orig, dest, sc, vc, svc, DATE, result["raw_envelope"])

                # Add to unified classic fares
                origin_name = ORIGIN_NAMES.get(orig, orig)
                dest_name = ORIGIN_NAMES.get(dest, dest)
                ship_class_name = SHIP_CLASS_NAMES.get(sc, sc)
                source_fname = f"fare_{orig}_{dest}_{sc}_vc{vc}_{DATE}.json"

                unified_fare_rows.append({
                    "origin": origin_name,
                    "destination": dest_name,
                    "shipClass": ship_class_name,
                    "vehicleClass": vc_name,
                    "departDate": DATE,
                    "departTime": time_range,
                    "kuota": quota,
                    "fareAmount": amt,
                    "totalFare": amt,
                    "currency": "IDR",
                    "sourceFile": source_fname,
                    "_sort_key": (orig, dest, sc, int(vc)),
                })

                formatted_amt = f"Rp {amt:,}" if amt else "?"
                print(f"[{completed:3d}/{total_tasks}] ✅ {od_display} {sc_display} {svc_label:11s} {vc_display:4s} ({vc_name:13s}): {time_range} | {formatted_amt} (kuota {quota})")
            elif result["success"]:
                stats["empty"] += 1
                print(f"[{completed:3d}/{total_tasks}] ⬜ {od_display} {sc_display} {svc_label:11s} {vc_display:4s} ({vc_name:13s}): empty/not_applicable")
            else:
                stats["failed"] += 1
                print(f"[{completed:3d}/{total_tasks}] ❌ {od_display} {sc_display} {svc_label:11s} {vc_display:4s} ({vc_name:13s}): {result.get('error')}")

            all_matrix_rows.append(matrix_row)
            time.sleep(random.uniform(0.3, 0.7))

    # ── Summary ────────────────────────────────────────────────
    print("\n" + "=" * 75)
    print("SCRAPE COMPLETE SUMMARY")
    print("=" * 75)
    print(f"  Success (valid fares found): {stats['success']} (all 6 ODxShip × 12 vehicle classes)")
    print(f"  Empty (PejalanKaki + VC):    {stats['empty']}")
    print(f"  Failed / errors:             {stats['failed']}")
    print(f"  Total tested:                {completed}/{total_tasks}")
    print("=" * 75)

    # ── Export Detailed Matrix CSV ──────────────────────────────
    matrix_csv_path = EXPORTS_DIR / f"unified_fares_ferizy_classic_all_{DATE}.csv"
    matrix_fields = [
        "route", "ship_class", "service", "vehicle_class", "vehicle_class_name",
        "depart_date", "depart_time", "available_quota", "sample_total", "currency",
        "status", "fare_count", "sample_quota"
    ]
    # Sort matrix rows systematically
    all_matrix_rows.sort(key=lambda r: (r["route"], r["ship_class"], r["service"], int(r["vehicle_class"].replace("VC", ""))))
    with open(matrix_csv_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=matrix_fields)
        writer.writeheader()
        writer.writerows(all_matrix_rows)
    print(f"\nMatrix CSV written: {matrix_csv_path} ({len(all_matrix_rows)} rows)")

    # ── Export Unified Classic Fares CSV ────────────────────────
    unified_fares_path = EXPORTS_DIR / "unified_fares_ferizy_classic.csv"
    unified_fields = [
        "origin", "destination", "shipClass", "vehicleClass", "departDate",
        "departTime", "kuota", "fareAmount", "totalFare", "currency", "sourceFile"
    ]
    # Sort unified fares: origin, destination, shipClass, vehicleClass ID
    unified_fare_rows.sort(key=lambda r: r["_sort_key"])
    # Remove temporary sorting key
    for r in unified_fare_rows:
        r.pop("_sort_key", None)

    with open(unified_fares_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=unified_fields)
        writer.writeheader()
        writer.writerows(unified_fare_rows)
    print(f"Unified fares CSV updated: {unified_fares_path} ({len(unified_fare_rows)} live fare rows)")


if __name__ == "__main__":
    main()
